stages:
- deploy

deploy to production:
  stage: deploy
  script: 
          kubectl create -f mysql-svc-deploy.yaml 
          kubectl create -f wp-svc-deploy.yaml 
          kubectl create -f mysql-app-deploy.yaml 
          kubectl create -f wp-app-deploy.yaml  
  environment:
    name: deploy-production