stages:
- deploy

deploy to production:
  stage: deploy
  image: alpine
  script: 
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl create -f mysql-svc-deploy.yaml 
          kubectl create -f wp-svc-deploy.yaml 
          kubectl create -f mysql-app-deploy.yaml 
          kubectl create -f wp-app-deploy.yaml  
  environment:
    name: deploy-production